/*
 * This file is generated by jOOQ.
 */
package onlinetutoring.com.teamelevenbackend.entity.tables.daos;


import java.time.LocalTime;
import java.util.List;
import java.util.Optional;

import onlinetutoring.com.teamelevenbackend.entity.tables.AvailableHours;
import onlinetutoring.com.teamelevenbackend.entity.tables.records.AvailableHoursRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AvailableHoursDao extends DAOImpl<AvailableHoursRecord, onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours, Integer> {

    /**
     * Create a new AvailableHoursDao without any configuration
     */
    public AvailableHoursDao() {
        super(AvailableHours.AVAILABLE_HOURS, onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours.class);
    }

    /**
     * Create a new AvailableHoursDao with an attached configuration
     */
    public AvailableHoursDao(Configuration configuration) {
        super(AvailableHours.AVAILABLE_HOURS, onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours.class, configuration);
    }

    @Override
    public Integer getId(onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours object) {
        return object.getTutorId();
    }

    /**
     * Fetch records that have <code>tutor_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours> fetchRangeOfTutorId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AvailableHours.AVAILABLE_HOURS.TUTOR_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tutor_id IN (values)</code>
     */
    public List<onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours> fetchByTutorId(Integer... values) {
        return fetch(AvailableHours.AVAILABLE_HOURS.TUTOR_ID, values);
    }

    /**
     * Fetch a unique record that has <code>tutor_id = value</code>
     */
    public onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours fetchOneByTutorId(Integer value) {
        return fetchOne(AvailableHours.AVAILABLE_HOURS.TUTOR_ID, value);
    }

    /**
     * Fetch a unique record that has <code>tutor_id = value</code>
     */
    public Optional<onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours> fetchOptionalByTutorId(Integer value) {
        return fetchOptional(AvailableHours.AVAILABLE_HOURS.TUTOR_ID, value);
    }

    /**
     * Fetch records that have <code>start_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours> fetchRangeOfStartTime(LocalTime lowerInclusive, LocalTime upperInclusive) {
        return fetchRange(AvailableHours.AVAILABLE_HOURS.START_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours> fetchByStartTime(LocalTime... values) {
        return fetch(AvailableHours.AVAILABLE_HOURS.START_TIME, values);
    }

    /**
     * Fetch records that have <code>end_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours> fetchRangeOfEndTime(LocalTime lowerInclusive, LocalTime upperInclusive) {
        return fetchRange(AvailableHours.AVAILABLE_HOURS.END_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>end_time IN (values)</code>
     */
    public List<onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours> fetchByEndTime(LocalTime... values) {
        return fetch(AvailableHours.AVAILABLE_HOURS.END_TIME, values);
    }

    /**
     * Fetch records that have <code>day_of_week BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours> fetchRangeOfDayOfWeek(String lowerInclusive, String upperInclusive) {
        return fetchRange(AvailableHours.AVAILABLE_HOURS.DAY_OF_WEEK, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>day_of_week IN (values)</code>
     */
    public List<onlinetutoring.com.teamelevenbackend.entity.tables.pojos.AvailableHours> fetchByDayOfWeek(String... values) {
        return fetch(AvailableHours.AVAILABLE_HOURS.DAY_OF_WEEK, values);
    }
}
