/*
 * This file is generated by jOOQ.
 */
package onlinetutoring.com.teamelevenbackend.entity;


import onlinetutoring.com.teamelevenbackend.entity.tables.Internal;
import onlinetutoring.com.teamelevenbackend.entity.tables.records.InternalRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<InternalRecord> INTERNAL_PKEY = org.jooq.impl.Internal.createUniqueKey(Internal.INTERNAL, DSL.name("internal_pkey"), new TableField[] { Internal.INTERNAL.ID }, true);
}
