/*
 * This file is generated by jOOQ.
 */
package onlinetutoring.com.teamelevenbackend.entity;


import onlinetutoring.com.teamelevenbackend.entity.routines.Checkifnotstudent;
import onlinetutoring.com.teamelevenbackend.entity.routines.Checkifnottutor;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.checkifnotstudent</code>
     */
    public static Boolean checkifnotstudent(
          Configuration configuration
        , Integer _Id
    ) {
        Checkifnotstudent f = new Checkifnotstudent();
        f.set_Id(_Id);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.checkifnotstudent</code> as a field.
     */
    public static Field<Boolean> checkifnotstudent(
          Integer _Id
    ) {
        Checkifnotstudent f = new Checkifnotstudent();
        f.set_Id(_Id);

        return f.asField();
    }

    /**
     * Get <code>public.checkifnotstudent</code> as a field.
     */
    public static Field<Boolean> checkifnotstudent(
          Field<Integer> _Id
    ) {
        Checkifnotstudent f = new Checkifnotstudent();
        f.set_Id(_Id);

        return f.asField();
    }

    /**
     * Call <code>public.checkifnottutor</code>
     */
    public static Boolean checkifnottutor(
          Configuration configuration
        , Integer _Id
    ) {
        Checkifnottutor f = new Checkifnottutor();
        f.set_Id(_Id);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.checkifnottutor</code> as a field.
     */
    public static Field<Boolean> checkifnottutor(
          Integer _Id
    ) {
        Checkifnottutor f = new Checkifnottutor();
        f.set_Id(_Id);

        return f.asField();
    }

    /**
     * Get <code>public.checkifnottutor</code> as a field.
     */
    public static Field<Boolean> checkifnottutor(
          Field<Integer> _Id
    ) {
        Checkifnottutor f = new Checkifnottutor();
        f.set_Id(_Id);

        return f.asField();
    }
}
