/*
 * This file is generated by jOOQ.
 */
package onlinetutoring.com.teamelevenbackend.entity;


import onlinetutoring.com.teamelevenbackend.entity.tables.Appointments;
import onlinetutoring.com.teamelevenbackend.entity.tables.AvailableHours;
import onlinetutoring.com.teamelevenbackend.entity.tables.Students;
import onlinetutoring.com.teamelevenbackend.entity.tables.Tutors;
import onlinetutoring.com.teamelevenbackend.entity.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.appointments</code>.
     */
    public static final Appointments APPOINTMENTS = Appointments.APPOINTMENTS;

    /**
     * The table <code>public.available_hours</code>.
     */
    public static final AvailableHours AVAILABLE_HOURS = AvailableHours.AVAILABLE_HOURS;

    /**
     * The table <code>public.students</code>.
     */
    public static final Students STUDENTS = Students.STUDENTS;

    /**
     * The table <code>public.tutors</code>.
     */
    public static final Tutors TUTORS = Tutors.TUTORS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
