/*
 * This file is generated by jOOQ.
 */
package onlinetutoring.com.teamelevenbackend.entity;


import onlinetutoring.com.teamelevenbackend.entity.tables.Internal;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.internal</code>.
     */
    public static final Internal INTERNAL = Internal.INTERNAL;
}
