/*
 * This file is generated by jOOQ.
 */
package onlinetutoring.com.teamelevenbackend.entity.routines;


import onlinetutoring.com.teamelevenbackend.entity.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Checkifnotstudent extends AbstractRoutine<Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.checkifnotstudent.RETURN_VALUE</code>.
     */
    public static final Parameter<Boolean> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.BOOLEAN, false, false);

    /**
     * The parameter <code>public.checkifnotstudent._id</code>.
     */
    public static final Parameter<Integer> _ID = Internal.createParameter("_id", SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Checkifnotstudent() {
        super("checkifnotstudent", Public.PUBLIC, SQLDataType.BOOLEAN);

        setReturnParameter(RETURN_VALUE);
        addInParameter(_ID);
    }

    /**
     * Set the <code>_id</code> parameter IN value to the routine
     */
    public void set_Id(Integer value) {
        setValue(_ID, value);
    }

    /**
     * Set the <code>_id</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public Checkifnotstudent set_Id(Field<Integer> field) {
        setField(_ID, field);
        return this;
    }
}
