/*
 * This file is generated by jOOQ.
 */
package onlinetutoring.com.teamelevenbackend.entity.tables.records;


import onlinetutoring.com.teamelevenbackend.entity.tables.Internal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InternalRecord extends UpdatableRecordImpl<InternalRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.internal.id</code>.
     */
    public InternalRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.internal.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.internal.name</code>.
     */
    public InternalRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.internal.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Internal.INTERNAL.ID;
    }

    @Override
    public Field<String> field2() {
        return Internal.INTERNAL.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public InternalRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public InternalRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public InternalRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InternalRecord
     */
    public InternalRecord() {
        super(Internal.INTERNAL);
    }

    /**
     * Create a detached, initialised InternalRecord
     */
    public InternalRecord(Integer id, String name) {
        super(Internal.INTERNAL);

        setId(id);
        setName(name);
    }

    /**
     * Create a detached, initialised InternalRecord
     */
    public InternalRecord(onlinetutoring.com.teamelevenbackend.entity.tables.pojos.Internal value) {
        super(Internal.INTERNAL);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
        }
    }
}
