/*
 * This file is generated by jOOQ.
 */
package onlinetutoring.com.teamelevenbackend.entity.tables.pojos;


import java.io.Serializable;
import java.time.LocalTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AvailableHours implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer tutorId;
    private LocalTime startTime;
    private LocalTime endTime;
    private String dayOfWeek;

    public AvailableHours() {}

    public AvailableHours(AvailableHours value) {
        this.tutorId = value.tutorId;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.dayOfWeek = value.dayOfWeek;
    }

    public AvailableHours(
        Integer tutorId,
        LocalTime startTime,
        LocalTime endTime,
        String dayOfWeek
    ) {
        this.tutorId = tutorId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.dayOfWeek = dayOfWeek;
    }

    /**
     * Getter for <code>public.available_hours.tutor_id</code>.
     */
    public Integer getTutorId() {
        return this.tutorId;
    }

    /**
     * Setter for <code>public.available_hours.tutor_id</code>.
     */
    public AvailableHours setTutorId(Integer tutorId) {
        this.tutorId = tutorId;
        return this;
    }

    /**
     * Getter for <code>public.available_hours.start_time</code>.
     */
    public LocalTime getStartTime() {
        return this.startTime;
    }

    /**
     * Setter for <code>public.available_hours.start_time</code>.
     */
    public AvailableHours setStartTime(LocalTime startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Getter for <code>public.available_hours.end_time</code>.
     */
    public LocalTime getEndTime() {
        return this.endTime;
    }

    /**
     * Setter for <code>public.available_hours.end_time</code>.
     */
    public AvailableHours setEndTime(LocalTime endTime) {
        this.endTime = endTime;
        return this;
    }

    /**
     * Getter for <code>public.available_hours.day_of_week</code>.
     */
    public String getDayOfWeek() {
        return this.dayOfWeek;
    }

    /**
     * Setter for <code>public.available_hours.day_of_week</code>.
     */
    public AvailableHours setDayOfWeek(String dayOfWeek) {
        this.dayOfWeek = dayOfWeek;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AvailableHours other = (AvailableHours) obj;
        if (this.tutorId == null) {
            if (other.tutorId != null)
                return false;
        }
        else if (!this.tutorId.equals(other.tutorId))
            return false;
        if (this.startTime == null) {
            if (other.startTime != null)
                return false;
        }
        else if (!this.startTime.equals(other.startTime))
            return false;
        if (this.endTime == null) {
            if (other.endTime != null)
                return false;
        }
        else if (!this.endTime.equals(other.endTime))
            return false;
        if (this.dayOfWeek == null) {
            if (other.dayOfWeek != null)
                return false;
        }
        else if (!this.dayOfWeek.equals(other.dayOfWeek))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.tutorId == null) ? 0 : this.tutorId.hashCode());
        result = prime * result + ((this.startTime == null) ? 0 : this.startTime.hashCode());
        result = prime * result + ((this.endTime == null) ? 0 : this.endTime.hashCode());
        result = prime * result + ((this.dayOfWeek == null) ? 0 : this.dayOfWeek.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AvailableHours (");

        sb.append(tutorId);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(dayOfWeek);

        sb.append(")");
        return sb.toString();
    }
}
