/*
 * This file is generated by jOOQ.
 */
package onlinetutoring.com.teamelevenbackend.entity.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Students implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer[] favouriteTutorIds;
    private Integer year;

    public Students() {}

    public Students(Students value) {
        this.id = value.id;
        this.favouriteTutorIds = value.favouriteTutorIds;
        this.year = value.year;
    }

    public Students(
        Integer id,
        Integer[] favouriteTutorIds,
        Integer year
    ) {
        this.id = id;
        this.favouriteTutorIds = favouriteTutorIds;
        this.year = year;
    }

    /**
     * Getter for <code>public.students.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.students.id</code>.
     */
    public Students setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.students.favourite_tutor_ids</code>.
     */
    public Integer[] getFavouriteTutorIds() {
        return this.favouriteTutorIds;
    }

    /**
     * Setter for <code>public.students.favourite_tutor_ids</code>.
     */
    public Students setFavouriteTutorIds(Integer[] favouriteTutorIds) {
        this.favouriteTutorIds = favouriteTutorIds;
        return this;
    }

    /**
     * Getter for <code>public.students.year</code>.
     */
    public Integer getYear() {
        return this.year;
    }

    /**
     * Setter for <code>public.students.year</code>.
     */
    public Students setYear(Integer year) {
        this.year = year;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Students other = (Students) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.favouriteTutorIds == null) {
            if (other.favouriteTutorIds != null)
                return false;
        }
        else if (!Arrays.equals(this.favouriteTutorIds, other.favouriteTutorIds))
            return false;
        if (this.year == null) {
            if (other.year != null)
                return false;
        }
        else if (!this.year.equals(other.year))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.favouriteTutorIds == null) ? 0 : Arrays.hashCode(this.favouriteTutorIds));
        result = prime * result + ((this.year == null) ? 0 : this.year.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Students (");

        sb.append(id);
        sb.append(", ").append(Arrays.toString(favouriteTutorIds));
        sb.append(", ").append(year);

        sb.append(")");
        return sb.toString();
    }
}
