/*
 * This file is generated by jOOQ.
 */
package onlinetutoring.com.teamelevenbackend.entity.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tutors implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String[] subjects;

    public Tutors() {}

    public Tutors(Tutors value) {
        this.id = value.id;
        this.subjects = value.subjects;
    }

    public Tutors(
        Integer id,
        String[] subjects
    ) {
        this.id = id;
        this.subjects = subjects;
    }

    /**
     * Getter for <code>public.tutors.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.tutors.id</code>.
     */
    public Tutors setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.tutors.subjects</code>.
     */
    public String[] getSubjects() {
        return this.subjects;
    }

    /**
     * Setter for <code>public.tutors.subjects</code>.
     */
    public Tutors setSubjects(String[] subjects) {
        this.subjects = subjects;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Tutors other = (Tutors) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.subjects == null) {
            if (other.subjects != null)
                return false;
        }
        else if (!Arrays.equals(this.subjects, other.subjects))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.subjects == null) ? 0 : Arrays.hashCode(this.subjects));
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tutors (");

        sb.append(id);
        sb.append(", ").append(Arrays.toString(subjects));

        sb.append(")");
        return sb.toString();
    }
}
