/*
 * This file is generated by jOOQ.
 */
package onlinetutoring.com.teamelevenbackend.entity.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String fName;
    private String lName;
    private String email;
    private String password;
    private Integer totalHours;
    private Boolean tutor;
    private String profilePic;
    private String aboutMe;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.fName = value.fName;
        this.lName = value.lName;
        this.email = value.email;
        this.password = value.password;
        this.totalHours = value.totalHours;
        this.tutor = value.tutor;
        this.profilePic = value.profilePic;
        this.aboutMe = value.aboutMe;
    }

    public Users(
        Integer id,
        String fName,
        String lName,
        String email,
        String password,
        Integer totalHours,
        Boolean tutor,
        String profilePic,
        String aboutMe
    ) {
        this.id = id;
        this.fName = fName;
        this.lName = lName;
        this.email = email;
        this.password = password;
        this.totalHours = totalHours;
        this.tutor = tutor;
        this.profilePic = profilePic;
        this.aboutMe = aboutMe;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.users.id</code>.
     */
    public Users setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.users.f_name</code>.
     */
    public String getFName() {
        return this.fName;
    }

    /**
     * Setter for <code>public.users.f_name</code>.
     */
    public Users setFName(String fName) {
        this.fName = fName;
        return this;
    }

    /**
     * Getter for <code>public.users.l_name</code>.
     */
    public String getLName() {
        return this.lName;
    }

    /**
     * Setter for <code>public.users.l_name</code>.
     */
    public Users setLName(String lName) {
        this.lName = lName;
        return this;
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.users.email</code>.
     */
    public Users setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>public.users.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.users.password</code>.
     */
    public Users setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>public.users.total_hours</code>.
     */
    public Integer getTotalHours() {
        return this.totalHours;
    }

    /**
     * Setter for <code>public.users.total_hours</code>.
     */
    public Users setTotalHours(Integer totalHours) {
        this.totalHours = totalHours;
        return this;
    }

    /**
     * Getter for <code>public.users.tutor</code>.
     */
    public Boolean getTutor() {
        return this.tutor;
    }

    /**
     * Setter for <code>public.users.tutor</code>.
     */
    public Users setTutor(Boolean tutor) {
        this.tutor = tutor;
        return this;
    }

    /**
     * Getter for <code>public.users.profile_pic</code>.
     */
    public String getProfilePic() {
        return this.profilePic;
    }

    /**
     * Setter for <code>public.users.profile_pic</code>.
     */
    public Users setProfilePic(String profilePic) {
        this.profilePic = profilePic;
        return this;
    }

    /**
     * Getter for <code>public.users.about_me</code>.
     */
    public String getAboutMe() {
        return this.aboutMe;
    }

    /**
     * Setter for <code>public.users.about_me</code>.
     */
    public Users setAboutMe(String aboutMe) {
        this.aboutMe = aboutMe;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Users other = (Users) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.fName == null) {
            if (other.fName != null)
                return false;
        }
        else if (!this.fName.equals(other.fName))
            return false;
        if (this.lName == null) {
            if (other.lName != null)
                return false;
        }
        else if (!this.lName.equals(other.lName))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.totalHours == null) {
            if (other.totalHours != null)
                return false;
        }
        else if (!this.totalHours.equals(other.totalHours))
            return false;
        if (this.tutor == null) {
            if (other.tutor != null)
                return false;
        }
        else if (!this.tutor.equals(other.tutor))
            return false;
        if (this.profilePic == null) {
            if (other.profilePic != null)
                return false;
        }
        else if (!this.profilePic.equals(other.profilePic))
            return false;
        if (this.aboutMe == null) {
            if (other.aboutMe != null)
                return false;
        }
        else if (!this.aboutMe.equals(other.aboutMe))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.fName == null) ? 0 : this.fName.hashCode());
        result = prime * result + ((this.lName == null) ? 0 : this.lName.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.totalHours == null) ? 0 : this.totalHours.hashCode());
        result = prime * result + ((this.tutor == null) ? 0 : this.tutor.hashCode());
        result = prime * result + ((this.profilePic == null) ? 0 : this.profilePic.hashCode());
        result = prime * result + ((this.aboutMe == null) ? 0 : this.aboutMe.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(fName);
        sb.append(", ").append(lName);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(totalHours);
        sb.append(", ").append(tutor);
        sb.append(", ").append(profilePic);
        sb.append(", ").append(aboutMe);

        sb.append(")");
        return sb.toString();
    }
}
