/*
 * This file is generated by jOOQ.
 */
package onlinetutoring.com.teamelevenbackend.entity.tables;


import java.util.function.Function;

import onlinetutoring.com.teamelevenbackend.entity.Keys;
import onlinetutoring.com.teamelevenbackend.entity.Public;
import onlinetutoring.com.teamelevenbackend.entity.tables.records.InternalRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Internal extends TableImpl<InternalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.internal</code>
     */
    public static final Internal INTERNAL = new Internal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InternalRecord> getRecordType() {
        return InternalRecord.class;
    }

    /**
     * The column <code>public.internal.id</code>.
     */
    public final TableField<InternalRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.internal.name</code>.
     */
    public final TableField<InternalRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    private Internal(Name alias, Table<InternalRecord> aliased) {
        this(alias, aliased, null);
    }

    private Internal(Name alias, Table<InternalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.internal</code> table reference
     */
    public Internal(String alias) {
        this(DSL.name(alias), INTERNAL);
    }

    /**
     * Create an aliased <code>public.internal</code> table reference
     */
    public Internal(Name alias) {
        this(alias, INTERNAL);
    }

    /**
     * Create a <code>public.internal</code> table reference
     */
    public Internal() {
        this(DSL.name("internal"), null);
    }

    public <O extends Record> Internal(Table<O> child, ForeignKey<O, InternalRecord> key) {
        super(child, key, INTERNAL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<InternalRecord, Integer> getIdentity() {
        return (Identity<InternalRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<InternalRecord> getPrimaryKey() {
        return Keys.INTERNAL_PKEY;
    }

    @Override
    public Internal as(String alias) {
        return new Internal(DSL.name(alias), this);
    }

    @Override
    public Internal as(Name alias) {
        return new Internal(alias, this);
    }

    @Override
    public Internal as(Table<?> alias) {
        return new Internal(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Internal rename(String name) {
        return new Internal(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Internal rename(Name name) {
        return new Internal(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Internal rename(Table<?> name) {
        return new Internal(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
